config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  resources :venues

  resources :meetings

  resources :sponsors

  resources :exhibitor_categories

  resources :exhibitors
  
  resources :homes
  
  root :to => "homes#index"

end

app/models/exhibitor_category.rb
class ExhibitorCategory < ActiveRecord::Base
  attr_accessible :name
  
  validates :name, :presence => true
  
  has_many :exhibitors
   
	def full_name
		"#{name}"
	end
end

app/controllers/exhibitor_categories_controller.rb
class ExhibitorCategoriesController < ApplicationController
  # GET /exhibitor_categories
  # GET /exhibitor_categories.json
  def index
    @exhibitor_categories = ExhibitorCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exhibitor_categories }
    end
  end

  # GET /exhibitor_categories/1
  # GET /exhibitor_categories/1.json
  def show
    @exhibitor_category = ExhibitorCategory.find(params[:id])
	@listexhibitors = @exhibitor_category.exhibitors

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exhibitor_category }
    end
  end

  # GET /exhibitor_categories/new
  # GET /exhibitor_categories/new.json
  def new
    @exhibitor_category = ExhibitorCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exhibitor_category }
    end
  end

  # GET /exhibitor_categories/1/edit
  def edit
    @exhibitor_category = ExhibitorCategory.find(params[:id])
  end

  # POST /exhibitor_categories
  # POST /exhibitor_categories.json
  def create
    @exhibitor_category = ExhibitorCategory.new(params[:exhibitor_category])

    respond_to do |format|
      if @exhibitor_category.save
        format.html { redirect_to @exhibitor_category, notice: 'Exhibitor category was successfully created.' }
        format.json { render json: @exhibitor_category, status: :created, location: @exhibitor_category }
      else
        format.html { render action: "new" }
        format.json { render json: @exhibitor_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exhibitor_categories/1
  # PUT /exhibitor_categories/1.json
  def update
    @exhibitor_category = ExhibitorCategory.find(params[:id])

    respond_to do |format|
      if @exhibitor_category.update_attributes(params[:exhibitor_category])
        format.html { redirect_to @exhibitor_category, notice: 'Exhibitor category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exhibitor_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitor_categories/1
  # DELETE /exhibitor_categories/1.json
  def destroy
    @exhibitor_category = ExhibitorCategory.find(params[:id])
    @exhibitor_category.destroy

    respond_to do |format|
      format.html { redirect_to exhibitor_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exhibitor_categories_helper.rb
module ExhibitorCategoriesHelper
end

app/views/exhibitor_categories/_form.html.erb
<%= form_for(@exhibitor_category) do |f| %>
  <% if @exhibitor_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibitor_category.errors.count, "error") %> prohibited this exhibitor_category from being saved:</h2>

      <ul>
      <% @exhibitor_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exhibitor_categories/edit.html.erb
<h1>Editing exhibitor_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @exhibitor_category %> |
<%= link_to 'Back', exhibitor_categories_path %>

app/views/exhibitor_categories/index.html.erb
<h1>Listing exhibitor_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exhibitor_categories.each do |exhibitor_category| %>
  <tr>
    <td><%= exhibitor_category.name %></td>
    <td><%= link_to 'Show', exhibitor_category %></td>
    <td><%= link_to 'Edit', edit_exhibitor_category_path(exhibitor_category) %></td>
    <td><%= link_to 'Destroy', exhibitor_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exhibitor category', new_exhibitor_category_path %>

app/views/exhibitor_categories/new.html.erb
<h1>New exhibitor_category</h1>

<%= render 'form' %>

<%= link_to 'Back', exhibitor_categories_path %>

app/views/exhibitor_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exhibitor_category.name %>
</p>

<div id="floatbox">
	<b>Exhibitors:</b><br />
	<% @listexhibitors.each do |c| %>
		<%= link_to c.name, exhibitor_path(c.id) %> <br />
	<% end %>
</div>


<%= link_to 'Edit', edit_exhibitor_category_path(@exhibitor_category) %> |
<%= link_to 'Back', exhibitor_categories_path %>