config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  resources :venues

  resources :meetings

  resources :sponsors

  resources :exhibitor_categories

  resources :exhibitors
  
  resources :homes
  
  root :to => "homes#index"

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :venue_id, :sponsor_ids
  
	validates :end_date,  :presence => true
	validates :name, :presence => true
	validates :start_date, :presence => true
	
	has_many :contests
	belongs_to :venue
	has_and_belongs_to_many :sponsors
	has_many :exhibitors, :through => :sponsors
	has_many :exhibitedmeetings, :through => :sponsors, :source => :exhibitors
	
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])
	@meetingsponsors = @meeting.sponsors
	@meetingvenues = @meeting.venue
	@meetingcontests = @meeting.contests

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    params[:meeting][:sponsor_ids] ||= []
	@meeting = Meeting.find(params[:id])
	
    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
<%= f.label :venue_id %><br />
<%= f.collection_select :venue_id, Venue.all.collect, :id, :full_name, :prompt => "Select a Venue"%>
</div>
<div class="field"> 
    <%= f.label "Sponsors" %><br /> 
    <% Sponsor.find(:all).each do |c| %>
<div>
  <%= check_box_tag "meeting[sponsor_ids][]", c.id, @meeting.sponsors.include?(c) %>
  <%= c.name %>
</div>
<% end %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Venue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.name %></td>
    <td><%= meeting.start_date %></td>
    <td><%= meeting.end_date %></td>
    <td><%= meeting.venue.full_name %></td>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @meeting.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @meeting.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @meeting.end_date %>
</p>

<div id="floatbox">
	<b>Venues:</b><br />
	<%= link_to @meeting.venue.full_name, venue_path(@meeting.venue.id) %><br />
	<%= @meeting.venue.address %><br />
	<%= @meeting.venue.city %>, <%= @meeting.venue.state %> <%= @meeting.venue.zip %><br /><br /><br />
	<b>Sponsors:</b><br />
	<% @meetingsponsors.each do |c| %>
		<%= link_to c.full_name, sponsor_path(c.id) %> <br />
	<% end %><br /><br /><br />
	<b>Contests:</b><br />
	<% @meetingcontests.each do |c| %>
		<%= link_to c.prize, contest_path(c.id) %> <br />
	<% end %>
</div>


<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>