config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  resources :venues

  resources :meetings

  resources :sponsors

  resources :exhibitor_categories

  resources :exhibitors
  
  resources :homes
  
  root :to => "homes#index"

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  attr_accessible :end_date, :meeting_id, :present_to_win, :prize, :sponsor_id, :start_date
  
	validates :prize, :presence => true
	validates :start_date, :presence => true
	validates :end_date, :presence => true
	validates :sponsor_id, :presence => true
	validates :meeting_id, :presence => true

	belongs_to :sponsor
	belongs_to :meeting
  
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contests }
    end
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    @contest = Contest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contest }
    end
  end

  # GET /contests/new
  # GET /contests/new.json
  def new
    @contest = Contest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contest }
    end
  end

  # GET /contests/1/edit
  def edit
    @contest = Contest.find(params[:id])
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(params[:contest])

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render json: @contest, status: :created, location: @contest }
      else
        format.html { render action: "new" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contests/1
  # PUT /contests/1.json
  def update
    @contest = Contest.find(params[:id])

    respond_to do |format|
      if @contest.update_attributes(params[:contest])
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy

    respond_to do |format|
      format.html { redirect_to contests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prize %><br />
    <%= f.text_area :prize %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :present_to_win %><br />
    <%= f.check_box :present_to_win  %>
  </div>
  <div class="field">
    <%= f.label :sponsor_id %><br />
	<%= f.collection_select :sponsor_id, Sponsor.all.collect, :id, :name, :prompt => "Select a Sponsor" %>
  </div>
  <div class="field">
    <%= f.label :meeting_id %><br />
	<%= f.collection_select :meeting_id, Meeting.all.collect, :id, :name, :prompt => "Select a Meeting" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1>Listing contests</h1>

<table>
  <tr>
    <th>Prize</th>
	<th>Sponsor</th>
    <th>Entries Open</th>
    <th>Entries Closed</th>
	<th>Meeting</th>
    <th>Present to win?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contests.each do |contest| %>
  <tr>
    <td><%= contest.prize %></td>
	<td><%= contest.sponsor.full_name %></td>
    <td><%= contest.start_date %></td>
    <td><%= contest.end_date %></td>
	<td><%= link_to contest.meeting.name, meeting_path(contest.meeting.id) %></td>
    <td><%= contest.present_to_win ? "Yes" : "No" %></td>
    <td><%= link_to 'Show', contest %></td>
    <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
    <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prize:</b>
  <%= @contest.prize %>
</p>

<p>
  <b>Start date:</b>
  <%= @contest.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @contest.end_date %>
</p>

<p>
  <b>Present to win:</b>
  <%= @contest.present_to_win ? "Yes" : "No" %>
</p>

<p>
  <b>Sponsor:</b>
  <%= @contest.sponsor.full_name %>
</p>

<p>
  <b>Meeting:</b>
  <%= @contest.meeting.name %>
</p>


<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>