config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  resources :venues

  resources :meetings

  resources :sponsors

  resources :exhibitor_categories

  resources :exhibitors
  
  resources :homes
  
  root :to => "homes#index"

end

app/models/exhibitor.rb
class Exhibitor < ActiveRecord::Base
  attr_accessible :description, :exhibitor_category_id, :name, :sponsor_id
  
	validates :description, :presence => true
	validates :exhibitor_category_id, :presence => true
	validates :name, :presence => true
	
	belongs_to :exhibitor_category
	belongs_to :sponsor
	has_many :meetings, :through => :sponsor
	has_many :sponsoredmeetings, :through => :sponsor, :source => :meetings
end

app/controllers/exhibitors_controller.rb
class ExhibitorsController < ApplicationController
  # GET /exhibitors
  # GET /exhibitors.json
  def index
    @exhibitors = Exhibitor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exhibitors }
    end
  end

  # GET /exhibitors/1
  # GET /exhibitors/1.json
  def show
    @exhibitor = Exhibitor.find(params[:id])
	@sponsoredmeetings = @exhibitor.meetings

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exhibitor }
    end
  end

  # GET /exhibitors/new
  # GET /exhibitors/new.json
  def new
    @exhibitor = Exhibitor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exhibitor }
    end
  end

  # GET /exhibitors/1/edit
  def edit
    @exhibitor = Exhibitor.find(params[:id])
  end

  # POST /exhibitors
  # POST /exhibitors.json
  def create
    @exhibitor = Exhibitor.new(params[:exhibitor])

    respond_to do |format|
      if @exhibitor.save
        format.html { redirect_to @exhibitor, notice: 'Exhibitor was successfully created.' }
        format.json { render json: @exhibitor, status: :created, location: @exhibitor }
      else
        format.html { render action: "new" }
        format.json { render json: @exhibitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exhibitors/1
  # PUT /exhibitors/1.json
  def update
    @exhibitor = Exhibitor.find(params[:id])

    respond_to do |format|
      if @exhibitor.update_attributes(params[:exhibitor])
        format.html { redirect_to @exhibitor, notice: 'Exhibitor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exhibitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitors/1
  # DELETE /exhibitors/1.json
  def destroy
    @exhibitor = Exhibitor.find(params[:id])
    @exhibitor.destroy

    respond_to do |format|
      format.html { redirect_to exhibitors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exhibitors_helper.rb
module ExhibitorsHelper
end

app/views/exhibitors/_form.html.erb
<%= form_for(@exhibitor) do |f| %>
  <% if @exhibitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibitor.errors.count, "error") %> prohibited this exhibitor from being saved:</h2>

      <ul>
      <% @exhibitor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
<div class="field">
<%= f.label :sponsor_id %><br />
<%= f.collection_select :sponsor_id, Sponsor.all.collect, :id, :name, :prompt => "Select a Sponsor" %>
</div>
<div class="field">
<%= f.label :exhibitor_category_id %><br />
<%= f.collection_select :exhibitor_category_id, ExhibitorCategory.all.collect, :id, :name, :prompt => "Select a Category" %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exhibitors/edit.html.erb
<h1>Editing exhibitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @exhibitor %> |
<%= link_to 'Back', exhibitors_path %>

app/views/exhibitors/index.html.erb
<h1>Listing exhibitors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Sponsor</th>
    <th>Exhibitor Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exhibitors.each do |exhibitor| %>
  <tr>
    <td><%= exhibitor.name %></td>
    <td><%= exhibitor.description %></td>
    <td><%= exhibitor.sponsor ? "Yes" : "No" %></td>
    <td><%= exhibitor.exhibitor_category.full_name %></td>
    <td><%= link_to 'Show', exhibitor %></td>
    <td><%= link_to 'Edit', edit_exhibitor_path(exhibitor) %></td>
    <td><%= link_to 'Destroy', exhibitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exhibitor', new_exhibitor_path %>

app/views/exhibitors/new.html.erb
<h1>New exhibitor</h1>

<%= render 'form' %>

<%= link_to 'Back', exhibitors_path %>

app/views/exhibitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exhibitor.name %>
</p>

<p>
  <b>Description:</b>
  <%= @exhibitor.description %>
</p>

<p>
  <b>Sponsor:</b>
  <%= @exhibitor.sponsor.name if @exhibitor.sponsor %>
</p>
<p>
  <b>Exhibitor category:</b>
  <%= @exhibitor.exhibitor_category.full_name %>
</p>


<div id="floatbox">
	<b>Meetings:</b><br />
	<% @sponsoredmeetings.each do |c| %>
		<%= link_to c.name, meeting_path(c.id) %><br />
	<% end %>
</div>

<%= link_to 'Edit', edit_exhibitor_path(@exhibitor) %> |
<%= link_to 'Back', exhibitors_path %>